##exemplo: elk stack extraindo dados de um banco psql##
version: '3.3'

services:
## ELK stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment: 
      - discovery.type=single-node
    ports: 
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    ports:
      - 5601:5601
    links: 
      - "elasticsearch:elasticsearch"
      
  logstash_postgres:
    image: docker.elastic.co/logstash/logstash:6.4.2
    container_name: logstash
    environment:

    links: 
      - "postgres:postgres"
      - "elasticsearch:elasticsearch"
    volumes:
      - ./pipeline_postgres/:/usr/share/logstash/pipeline/
  
  # fscrawler: 
  #  image: shadiakiki1986/fscrawler:2.4
  #  container_name: fscrawler_GL
  #  links:
  #    - "elasticsearch:elasticsearch"
  #  volumes:
  #    - "./fscrawler/myjob:/usr/share/fscrawler/config/myjob"
  #  environment: 
  #    - --config_dir /usr/share/fscrawler/config 
